apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z notes-postgres 5432; do echo "waiting for notes-postgres"; sleep 2; done
      containers:
        - name: backend
          image: notes-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: notes-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: notes-app
spec:
  selector:
    app: notes-backend
  ports:
    - port: 3000
      targetPort: 3000
