apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-postgres
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-postgres
  template:
    metadata:
      labels:
        app: notes-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: notes-postgres
  namespace: notes-app
spec:
  selector:
    app: notes-postgres
  ports:
    - port: 5432
      targetPort: 5432
