apiVersion: v1
kind: Secret
metadata:
  name: notes-secret
  namespace: notes-app
type: Opaque
stringData:
  DB_USERNAME: notes_user
  DB_PASSWORD: notes_password
  JWT_SECRET: k3s_secret_jwt_key
  POSTGRES_USER: notes_user
  POSTGRES_PASSWORD: notes_password
  POSTGRES_DB: notes_db
